/** EUIX, HTML5, SVG, and Plugin tags that are not user-defined components. */
export const BUILTIN_TAGS = new Set([
    // Core EUIX Structure
    "uid_spec",
    "data_model",
    "state",
    "computed",
    "watch",
    "action",
    "actions",
    "action_def",
    "component",
    "component_def",
    "param",
    "arg",
    "arg_def",
    "step",
    "return",
    "slot",
    "template",
    "import",
    "imports",
    "use_script",
    "use_style",
    "use_plugin",

    // EUIX Control Flow & Layout
    "flex",
    "container",
    "card",
    "grid",
    "if",
    "else",
    "elif",
    "show",
    "for_each",
    "each",

    // Standard HTML Structure & Text
    "html",
    "head",
    "body",
    "title",
    "meta",
    "style",
    "script",
    "link",
    "base",
    "div",
    "span",
    "p",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "header",
    "footer",
    "main",
    "section",
    "article",
    "nav",
    "aside",
    "figure",
    "figcaption",
    "details",
    "summary",
    "dialog",
    "address",
    "hr",
    "br",
    "pre",
    "code",
    "blockquote",
    "cite",
    "q",
    "abbr",
    "time",
    "mark",
    "small",
    "strong",
    "b",
    "em",
    "i",
    "u",
    "s",
    "del",
    "ins",
    "sub",
    "sup",
    "kbd",
    "samp",
    "var",

    // HTML Lists & Tables
    "ul",
    "ol",
    "li",
    "dl",
    "dt",
    "dd",
    "table",
    "thead",
    "tbody",
    "tfoot",
    "tr",
    "th",
    "td",
    "caption",
    "col",
    "colgroup",

    // HTML Forms & Interactive
    "form",
    "input",
    "button",
    "textarea",
    "select",
    "option",
    "optgroup",
    "label",
    "fieldset",
    "legend",
    "datalist",
    "output",
    "progress",
    "meter",
    "a",

    // HTML Media & Embedded
    "img",
    "picture",
    "source",
    "audio",
    "video",
    "track",
    "canvas",
    "iframe",
    "embed",
    "object",

    // SVG Elements
    "svg",
    "path",
    "g",
    "circle",
    "rect",
    "line",
    "polygon",
    "polyline",
    "text",
    "tspan",
    "defs",
    "clipPath",
    "mask",
    "use",
    "symbol",
    "linearGradient",
    "radialGradient",
    "stop",
    "pattern",
    "filter",
    "feDropShadow",
    "feGaussianBlur",

    // Declarative Events
    "on_click",
    "on_change",
    "on_input",
    "on_submit",
    "on_mount",
    "on_unmount",
    "on_interval",
    "on_state_change",
    "on_keyup",
    "on_keydown",
    "on_keypress",
    "on_visible",
    "on_update",
    "on_mouseenter",
    "on_mouseleave",
    "on_mouseover",
    "on_focus",
    "on_blur",

    // API & SWR Plugins
    "api_config",
    "api_endpoint",
    "api_stream",
    "endpoint",
    "tag",
    "headers",
    "params",

    // Router Plugin
    "router",
    "route",
    "outlet",
    "link",

    // Navigator Plugin
    "navigator",
    "nav_item",

    // Chart Plugin
    "chart",
    "chart_axis",
    "chart_series",
    "chart_tooltip",
    "chart_legend",

    // Map / Leaflet Plugin
    "map",
    "marker",
    "popup",
    "tile_layer",

    // Date & Time Plugin
    "date",
    "time",
    "relative_time",
    "date_range",
    "date_config",

    // Dialog, Collapse, UI Plugins
    "collapse",
    "modal",
    "portal",
    "toast",
    "drawer",
    "badge",
    "avatar",
    "divider",
    "spacer",
    "tooltip",
    "dropdown",
    "tabs",
    "tab",
    "accordion",
    "accordion_item",
    "menu",
    "menu_item",

    // WebMCP, Live Region, Validation, Persistence, Animations
    "webmcp",
    "tool",
    "validation_rules",
    "field",
    "error_boundary",
    "fallback",
    "live_region",
    "description",
    "persistence",
    "persist",
    "animations",
    "animation_def",
    "keyframe",

    // Constants, Data Items, & API config children
    "constants",
    "const",
    "item",
    "index",
    "method",
    "url",
    "loading",
    "error",
    "item_map",
    "reset",
    "cache",
    "revalidate",
    "query",
    "headers",
    "params",
    "param_def",
    "prop_def",
    "state_item",

    // Workflow / Step / Helper XML tags
    "route_link",
    "route-link",
    "leaflet_map",
    "leaflet-map",
    "persisted_key",
    "persisted-key",
    "target_where",
    "target-where",
    "catch",
    "finally",
    "retry",
    "timeout",
    "delay",
    "focus",
    "target",
    "map_id",
    "lat",
    "lng",
    "zoom",
    "confirm",
    "value",
    "where",
    "fields",
    "operation",
    "body",
    "children",
    "root",
]);

/** True when tag could be a user component (registry match required). */
export function isPotentialComponentTag(tagName: string): boolean {
    const tag = tagName.toLowerCase();
    if (BUILTIN_TAGS.has(tag)) return false;
    if (tag.startsWith("on_") || tag.startsWith("chart_") || tag.startsWith("use_")) return false;
    return /^[a-z][a-z0-9_-]*$/i.test(tag);
}
