/**
 * src/compiler/index.js
 * High-performance XML compiler, AST code generator, and Vite/Rollup plugins for EUIX Engine.
 */

/**
 * Parses XML/HTML string into a lightweight AST node tree without browser DOMParser dependencies.
 * @param {string} xmlString
 * @returns {object} Root AST Node
 */
export function compileXmlToAst(xmlString) {
    if (!xmlString || typeof xmlString !== "string") {
        return null;
    }

    // 1. Strip XML declaration and clean comments
    let src = xmlString.replace(/<\?xml[\s\S]*?\?>/gi, "").trim();

    // 2. Protect CDATA blocks and <style>/<script> tags
    const cdataBlocks = [];
    src = src.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/gi, (_, content) => {
        cdataBlocks.push(content);
        return `___EUIX_CDATA_${cdataBlocks.length - 1}___`;
    });

    const root = { tag: "root", attrs: {}, children: [] };
    const stack = [root];
    let pos = 0;
    const len = src.length;

    const VOID_ELEMENTS = new Set([
        "area", "base", "br", "col", "embed", "hr", "img", "input",
        "link", "meta", "param", "source", "track", "wbr"
    ]);

    while (pos < len) {
        // Find next tag
        const tagStart = src.indexOf("<", pos);
        if (tagStart === -1) {
            // Remaining text
            const text = src.slice(pos).trim();
            if (text) {
                const current = stack[stack.length - 1];
                current.children.push(_restoreCdata(text, cdataBlocks));
            }
            break;
        }

        // Text before tag
        if (tagStart > pos) {
            const text = src.slice(pos, tagStart).trim();
            if (text) {
                const current = stack[stack.length - 1];
                current.children.push(_restoreCdata(text, cdataBlocks));
            }
        }

        // Check if comment
        if (src.startsWith("<!--", tagStart)) {
            const commentEnd = src.indexOf("-->", tagStart + 4);
            pos = commentEnd !== -1 ? commentEnd + 3 : len;
            continue;
        }

        // Find tag closing '>' while respecting quoted attribute strings
        let tagEnd = -1;
        let inQuote = null;
        for (let i = tagStart + 1; i < len; i++) {
            const char = src[i];
            if (char === '"' || char === "'") {
                if (inQuote === char) {
                    inQuote = null;
                } else if (!inQuote) {
                    inQuote = char;
                }
            } else if (char === ">" && !inQuote) {
                tagEnd = i;
                break;
            }
        }
        if (tagEnd === -1) break;

        const tagContent = src.slice(tagStart + 1, tagEnd).trim();
        pos = tagEnd + 1;

        // Closing tag
        if (tagContent.startsWith("/")) {
            const closeTag = tagContent.slice(1).trim().toLowerCase();
            if (stack.length > 1 && stack[stack.length - 1].tag.toLowerCase() === closeTag) {
                stack.pop();
            }
            continue;
        }

        // Opening or Self-closing tag
        const isSelfClosing = tagContent.endsWith("/") || VOID_ELEMENTS.has(tagContent.split(/[\s/]/)[0].toLowerCase());
        const cleanContent = tagContent.replace(/\/$/, "").trim();
        const spaceIdx = cleanContent.search(/\s/);
        const tagName = spaceIdx === -1 ? cleanContent : cleanContent.slice(0, spaceIdx);
        const attrsStr = spaceIdx === -1 ? "" : cleanContent.slice(spaceIdx).trim();

        const attrs = _parseAttributes(attrsStr);
        const node = {
            tag: tagName,
            attrs,
            children: [],
            isSelfClosing
        };

        const parent = stack[stack.length - 1];
        parent.children.push(node);

        if (!isSelfClosing) {
            stack.push(node);
        }
    }

    const effectiveRoot = root.children.length === 1 ? root.children[0] : root;
    return effectiveRoot;
}

function _parseAttributes(attrsStr) {
    const attrs = {};
    if (!attrsStr) return attrs;

    const regex = /([a-zA-Z0-9_\-:]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+)))?/g;
    let match;
    while ((match = regex.exec(attrsStr)) !== null) {
        const name = match[1];
        const val = match[2] !== undefined ? match[2] : match[3] !== undefined ? match[3] : match[4] !== undefined ? match[4] : "";
        attrs[name] = val;
    }
    return attrs;
}

function _restoreCdata(text, cdataBlocks) {
    return text.replace(/___EUIX_CDATA_(\d+)___/g, (_, idx) => cdataBlocks[parseInt(idx, 10)] || "");
}

/**
 * Compiles XML template into a JavaScript module (ESM) exporting AST, XML, and template functions.
 * @param {string} xmlString
 * @param {object} options
 * @returns {string} Compiled JavaScript code
 */
export function compileXmlToJs(xmlString, options = {}) {
    const ast = compileXmlToAst(xmlString);
    const astJson = JSON.stringify(ast);
    const xmlSafe = JSON.stringify(xmlString);

    return `// Generated by EUIX Compiler
export const ast = ${astJson};
export const xml = ${xmlSafe};
export default xml;
`;
}

/**
 * Vite plugin for EUIX Engine (.xml and .euix template pre-compilation).
 * @param {object} options
 * @returns {object} Vite plugin
 */
export function euixVitePlugin(options = {}) {
    return {
        name: "vite-plugin-euix",
        transform(code, id) {
            if (id.endsWith(".xml") || id.endsWith(".euix")) {
                const js = compileXmlToJs(code, options);
                return {
                    code: js,
                    map: { mappings: "" }
                };
            }
            return null;
        }
    };
}

/**
 * Rollup plugin alias for EUIX Engine.
 */
export const euixRollupPlugin = euixVitePlugin;
export const euixPlugin = euixVitePlugin;

export { generateXSDSchema, generateJsonSchema } from "./schemaGenerator.js";
export { generateComponentTypes } from "./typeGenerator.js";
