export { analyzeTarget } from "./analyze.js";
export { expandComposition, resolveImportPath } from "./euix/composition.js";
export { runDoctor } from "./doctor.js";
export { runDoctorCli, parseDoctorArgs } from "./cli/main.js";
export { buildDependencyEdges } from "./analysis/dependencies.js";
export { runDiagnostics } from "./diagnostics/index.js";
export { buildProject, createEmptyProject } from "./ir/project.js";
export { applyBaseline, loadBaseline, saveBaseline } from "./reporters/baseline.js";
export { doctorResultToSarif } from "./reporters/sarif.js";
export { doctorResultToJson } from "./reporters/json.js";
export { generateHtmlReport } from "./reporters/html.js";
export { RULE_CATALOG, getRuleMetadata, getRuleCategory, getRuleExplanation } from "./diagnostics/catalog.js";
export { applyFixes, collectFixes, collectEuix0001Fixes } from "./fixes/index.js";
export { attachFixesToDiagnostics } from "./fixes/attach.js";
export { scanProject } from "./scanner/index.js";
export type * from "./ir/types.js";
